version: "3.9"

services:
  db:
    image: "postgres"
    container_name: postgres-db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"